apiVersion: federated.artifactory.jfrog.m.crossplane.io/v1alpha1
kind: OpkgRepository
metadata:
  name: federated-opkg-example
spec:
  forProvider: {}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
