apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: MavenRepository
metadata:
  name: maven-crossplane-repository
spec:
  forProvider: {}
    # key: maven-crossplane-repository
  providerConfigRef:
    name: default
