apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: NuGetRepository
metadata:
  name: nuget-example-crossplane-local
spec:
  forProvider: {}
    # key: nuget-example-crossplane-local
  providerConfigRef:
    name: default
