apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: ConanRepository
metadata:
  name: conan-crossplane-repository
spec:
  forProvider: {}
    # key: conan-crossplane-repository
  providerConfigRef:
    name: default
