apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: TerraformModuleRepository
metadata:
  name: terraform-module-example-crossplane-local
spec:
  forProvider: {}
    # key: terraform-module-example-crossplane-local
  providerConfigRef:
    name: default
