apiVersion: remote.artifactory.jfrog.crossplane.io/v1alpha1
kind: TerraformRepository
metadata:
  name: terraform-example-crossplane-remote
spec:
  forProvider:
    url: https://terraform.example.com
  providerConfigRef:
    name: default
