apiVersion: federated.artifactory.jfrog.m.crossplane.io/v1alpha1
kind: HuggingfacemlRepository
metadata:
  name: federated-huggingfaceml-example
spec:
  forProvider: {}
  providerConfigRef:
    name: default
