// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AlpineRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AnsibleRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BowerRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CargoRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ChefRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CocoapodsRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ComposerRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CondaRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CranRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DebianRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DockerRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GemsRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GenericRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GitLFSRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GoRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GradleRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HelmOCIRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HelmRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HuggingfacemlRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IvyRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MavenRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NpmRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NugetRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OCIRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OpkgRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *P2Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PubRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PuppetRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PypiRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RPMRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SbtRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SwiftRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TerraformRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VcsRepository) Hub() {}
