apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: SbtRepository
metadata:
  name: sbt-crossplane-repository
spec:
  forProvider: {}
    # key: sbt-crossplane-repository
  providerConfigRef:
    name: default
