apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: VagrantRepository
metadata:
  name: vagrant-example-crossplane-local
spec:
  forProvider: {}
    # key: vagrant-example-crossplane-local
  providerConfigRef:
    name: default
