apiVersion: remote.artifactory.jfrog.crossplane.io/v1alpha1
kind: IvyRepository
metadata:
  name: ivy-example-crossplane-remote
spec:
  forProvider:
    url: https://example.com/ivy
  providerConfigRef:
    name: default
