apiVersion: remote.artifactory.jfrog.crossplane.io/v1alpha1
kind: PyPIRepository
metadata:
  name: pypi-example-crossplane-remote
spec:
  forProvider:
    url: https://pypi.example.com
  providerConfigRef:
    name: default
