apiVersion: artifactory.jfrog.crossplane.io/v1alpha1
kind: LocalPubRepository
metadata:
  name: pub-crossplane-repository
spec:
  forProvider: {}
    # key: pub-crossplane-repository
  providerConfigRef:
    name: default
