apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: PubRepository
metadata:
  name: pub-example-crossplane-local
spec:
  forProvider: {}
    # key: pub-example-crossplane-local
  providerConfigRef:
    name: default
