apiVersion: federated.artifactory.jfrog.m.crossplane.io/v1alpha1
kind: GitlfsRepository
metadata:
  name: federated-gitlfs-example
spec:
  forProvider: {}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
