apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: TerraformModuleRepository
metadata:
  name: terraform-module-crossplane-repository
spec:
  forProvider: {}
    # key: terraform-module-crossplane-repository
  providerConfigRef:
    name: default
