apiVersion: federated.artifactory.jfrog.m.crossplane.io/v1alpha1
kind: ComposerRepository
metadata:
  name: federated-composer-example
spec:
  forProvider: {}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
