apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: NPMRepository
metadata:
  name: npm-example-crossplane-local
spec:
  forProvider: {}
    # key: npm-example-crossplane-local
  providerConfigRef:
    name: default
