apiVersion: remote.artifactory.jfrog.crossplane.io/v1alpha1
kind: CondaRepository
metadata:
  name: conda-example-crossplane-remote
spec:
  forProvider:
    url: https://conda.example.com
    description: Example Conda remote repository
  providerConfigRef:
    name: default
