//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemProperties) DeepCopyInto(out *ItemProperties) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemProperties.
func (in *ItemProperties) DeepCopy() *ItemProperties {
	if in == nil {
		return nil
	}
	out := new(ItemProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ItemProperties) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPropertiesInitParameters) DeepCopyInto(out *ItemPropertiesInitParameters) {
	*out = *in
	if in.IsRecursive != nil {
		in, out := &in.IsRecursive, &out.IsRecursive
		*out = new(bool)
		**out = **in
	}
	if in.ItemPath != nil {
		in, out := &in.ItemPath, &out.ItemPath
		*out = new(string)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string][]*string, len(*in))
		for key, val := range *in {
			var outVal []*string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]*string, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(string)
						**out = **in
					}
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.RepoKey != nil {
		in, out := &in.RepoKey, &out.RepoKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPropertiesInitParameters.
func (in *ItemPropertiesInitParameters) DeepCopy() *ItemPropertiesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ItemPropertiesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPropertiesList) DeepCopyInto(out *ItemPropertiesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ItemProperties, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPropertiesList.
func (in *ItemPropertiesList) DeepCopy() *ItemPropertiesList {
	if in == nil {
		return nil
	}
	out := new(ItemPropertiesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ItemPropertiesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPropertiesObservation) DeepCopyInto(out *ItemPropertiesObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsRecursive != nil {
		in, out := &in.IsRecursive, &out.IsRecursive
		*out = new(bool)
		**out = **in
	}
	if in.ItemPath != nil {
		in, out := &in.ItemPath, &out.ItemPath
		*out = new(string)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string][]*string, len(*in))
		for key, val := range *in {
			var outVal []*string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]*string, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(string)
						**out = **in
					}
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.RepoKey != nil {
		in, out := &in.RepoKey, &out.RepoKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPropertiesObservation.
func (in *ItemPropertiesObservation) DeepCopy() *ItemPropertiesObservation {
	if in == nil {
		return nil
	}
	out := new(ItemPropertiesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPropertiesParameters) DeepCopyInto(out *ItemPropertiesParameters) {
	*out = *in
	if in.IsRecursive != nil {
		in, out := &in.IsRecursive, &out.IsRecursive
		*out = new(bool)
		**out = **in
	}
	if in.ItemPath != nil {
		in, out := &in.ItemPath, &out.ItemPath
		*out = new(string)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string][]*string, len(*in))
		for key, val := range *in {
			var outVal []*string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]*string, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(string)
						**out = **in
					}
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.RepoKey != nil {
		in, out := &in.RepoKey, &out.RepoKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPropertiesParameters.
func (in *ItemPropertiesParameters) DeepCopy() *ItemPropertiesParameters {
	if in == nil {
		return nil
	}
	out := new(ItemPropertiesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPropertiesSpec) DeepCopyInto(out *ItemPropertiesSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPropertiesSpec.
func (in *ItemPropertiesSpec) DeepCopy() *ItemPropertiesSpec {
	if in == nil {
		return nil
	}
	out := new(ItemPropertiesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemPropertiesStatus) DeepCopyInto(out *ItemPropertiesStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemPropertiesStatus.
func (in *ItemPropertiesStatus) DeepCopy() *ItemPropertiesStatus {
	if in == nil {
		return nil
	}
	out := new(ItemPropertiesStatus)
	in.DeepCopyInto(out)
	return out
}
