apiVersion: federated.artifactory.jfrog.m.crossplane.io/v1alpha1
kind: HelmRepository
metadata:
  name: federated-helm-example
spec:
  forProvider: {}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
