apiVersion: federated.artifactory.jfrog.m.crossplane.io/v1alpha1
kind: DockerV2Repository
metadata:
  name: federated-dockerv2-example
spec:
  forProvider: {}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
