apiVersion: remote.artifactory.jfrog.crossplane.io/v1alpha1
kind: ChefRepository
metadata:
  name: chef-example-crossplane-remote
spec:
  forProvider:
    url: https://chef.example.com
  providerConfigRef:
    name: default
