apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: GemsRepository
metadata:
  name: gems-example-crossplane-local
spec:
  forProvider: {}
    # key: gems-example-crossplane-local
  providerConfigRef:
    name: default
