apiVersion: remote.artifactory.jfrog.crossplane.io/v1alpha1
kind: ConanRepository
metadata:
  name: conan-example-crossplane-remote
spec:
  forProvider:
    url: https://conan.example.com
  providerConfigRef:
    name: default
