// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AnonymousUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ItemProperties) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Keypair) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalAnsibleRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalDockerV2Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalGenericRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalOCIRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalTerraformProviderRepository) Hub() {}
