// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AnonymousUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Backup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ItemProperties) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Keypair) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalAlpineRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalAnsibleRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalBowerRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalCargoRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalChefRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalCocoapodsRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalComposerRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalConanRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalCondaRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalCranRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalDebianRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalDockerV1Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalDockerV2Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalGenericRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalGradleRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalHuggingfacemlRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalIvyRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalMachinelearningRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalMavenRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalNpmRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalNugetRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalOCIRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalOpkgRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalPubRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalPuppetRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalPypiRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalRPMRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalSbtRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalSwiftRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalTerraformbackendRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalTerraformModuleRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalTerraformProviderRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LocalVagrantRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteAlpineRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteAnsibleRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteBowerRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteCargoRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteChefRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteCocoapodsRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteComposerRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteCondaRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteCranRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteDebianRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteDockerRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteGemsRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteGenericRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteGitLFSRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteGoRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteGradleRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteHelmOCIRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteHelmRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteHuggingfacemlRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteIvyRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteMavenRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteNpmRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteNugetRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteOCIRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteOpkgRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteP2Repository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemotePubRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemotePuppetRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemotePyPIRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteRPMRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteSBTRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteSwiftRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteTerraformRepository) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RemoteVCSRepository) Hub() {}
