apiVersion: remote.remote.artifactory.jfrog.crossplane.io/v1alpha1
kind: AlpineRepository
metadata:
  name: alpine-remote-repository
spec:
  forProvider: {}
    # key: alpine-remote-repository
  providerConfigRef:
    name: default
