apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: HuggingFaceMLRepository
metadata:
  name: huggingfaceml-example-crossplane-local
spec:
  forProvider: {}
    # key: huggingfaceml-example-crossplane-local
  providerConfigRef:
    name: default
