apiVersion: federated.artifactory.jfrog.m.crossplane.io/v1alpha1
kind: DockerRepository
metadata:
  name: federated-docker-example
spec:
  forProvider: {}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
