apiVersion: local.artifactory.jfrog.crossplane.io/v1alpha1
kind: SwiftRepository
metadata:
  name: swift-example-crossplane-local
spec:
  forProvider: {}
    # key: swift-example-crossplane-local
  providerConfigRef:
    name: default
