apiVersion: federated.artifactory.jfrog.m.crossplane.io/v1alpha1
kind: SwiftRepository
metadata:
  name: federated-swift-example
spec:
  forProvider: {}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
